### ISSUE TITLE
親子関係をつけたオブジェクトの回転の中心問題

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/dev008#1]
# 親子関係をつけたオブジェクトの回転の中心問題
## 問題点
- 親子関係をつけたオブジェクトをそれぞれの中心で回転させたいです。なのに、親の中心で回ってしまいます。アドバイスください。
<img width="276" alt="2018-09-12 19 15 44" src="https://user-images.githubusercontent.com/28649401/45418802-69cfc400-b6c0-11e8-969f-bdc00caa1e94.png">
<img width="758" alt="2018-09-12 19 18 19" src="https://user-images.githubusercontent.com/28649401/45418886-a13e7080-b6c0-11e8-9eb5-62611b33b6b3.png">

**Comment by m1ya** [comment]
スクリプトで書いているのなら子供それぞれにアタッチするのが好きかと思います！
コンポーネントって同じものをいろいろなところで使い回せるのがいいところでもあるのですね！
やり方はざっくり2つあるかなーと思ってて

1. 回転させたいオブジェクトを全部選択（ShiftとかCommandとか押しながら）して、Inspectorからスクリプトをアタッチしてあげる（複数のオブジェクトにまとめて同じ動作ができる！transformの変更とかも一気にできるので把握しておくと便利）
2. 置いてあるオブジェクトをprefab（プレファブ）にして、prefabにスクリプトをつける！オブジェクトを作り直す必要があるけれど、増やす時に便利！

どちらの方法も知って置いてほしいものなので余裕があったら両方試して見てどんな感じなのか見てほしいです！

**Comment by fummicc1** [comment]
なるほど！
